[package]
name = "check"
version = "0.1.0"
authors = ["Balazs Horvath"]
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
regex = "1.10.5"
crossterm = "0.27.0"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5.9", features = ["derive"] }
anyhow = { version = "1.0.86", features = ["backtrace"] }
toml = "0.8.14"
