[package]
name = "extract-metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
safetensors = "0.4.3"
memmap2 = "0.9.4"
serde_json = "1.0"
walkdir = "2.5.0"
anyhow = "1.0.86"
