[workspace]
members = [
  "keep-tokens",
  "format-json",
  "check-for-attributes",
  "convert-e621-json-to-caption",
]

[package]
name = "dataset-tools-rs"
version = "0.1.0"
authors = ["Balazs Horvath"]
edition = "2021"

[dependencies]
regex = "1.10.5"
walkdir = "2.5.0"
crossterm = "0.27.0"
serde_json = "1.0.117"
