[workspace]
resolver = "2"
members = [
  "check-for-attributes",
  "check-for-cringe-summaries",
  "check-for-optimizations",
  "check-for-pedantic",
  "check-for-unwrap",
  "compress-exe",
  "convert-e621-json-to-caption",
  "create-empty-caption-files",
  "delete-url-files",
  "extract-metadata",
  "format-json",
  "hotdogaug",
  "insert-pedantic",
  "keep-tokens",
  "letterbox-remover",
  "remove-extra-file-extensions",
  "search-for-empty-captions",
  "search-for-superscript-numbers",
]

[package]
name = "dataset-tools"
version = "0.1.0"
authors = ["Balazs Horvath"]
edition = "2021"
license = "MIT"

[dependencies]
# Command Line Argument Parser for Rust
log = "0.4.22"
env_logger = "0.11.3"
clap = { version = "4.5.8", features = ["derive"] }
regex = "1.10.5"
walkdir = "2.5.0"
crossterm = "0.27.0"
serde_json = "1.0.120"
safetensors = "0.4.3"
memmap2 = "0.9.4"
anyhow = "1.0.86"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies but not for our code:
[profile.dev.package."*"]
opt-level = 3
