[package]
name = "simpletuner2kohya"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
walkdir = "2.5.0"
tokio = { version = "1.41.1", features = ["full"] }
md-5 = "0.10.6"
anyhow = { version = "1.0.93", features = ["backtrace"] }
