[package]
name = "simpletuner2kohya"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset_tools = { path = ".." }
tokio = { version = "1.41.1", features = ["full"] }
anyhow = "1.0.93"
serde_json = "1.0.133"
regex = "1.11.1"
