[package]
name = "remove-transparency"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
tokio = { version = "1.40.0", features = ["full"] }
image = "0.25.2"
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
