[package]
name = "remove-transparency"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
tokio = { version = "1.41.1", features = ["full"] }
image = "0.25.5"
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
