[package]
name = "insert-pedantic"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
anyhow = { version = "1.0.86", features = ["backtrace"] }
tokio = { version = "1.39.2", features = ["full"] }
