[package]
name = "check-for-optimizations"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
anyhow = { version = "1.0.86", features = ["backtrace"] }
toml = "0.8.14"
tokio = { version = "1.38.0", features = ["full"] }
