[package]
name = "convert-caption-json-to-txt"
version = "0.1.0"
authors = ["Balazs Horvath"]
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
walkdir = "2.5.0"
serde_json = "1.0.121"
tokio = { version = "1.39.2", features = ["full"] }
