[package]
name = "compress-exe"
version = "0.1.0"
authors = ["Balazs Horvath"]
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
tokio = { version = "1.38.1", features = ["full"] }
anyhow = { version = "1.0.86", features = ["backtrace"] }
