[package]
name = "compress-exe"
version = "0.1.0"
authors = ["Balazs Horvath"]
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
tokio = { version = "1.38.0", features = ["full"] }
anyhow = "1.0.86"
