[package]
name = "check-for-unwrap"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
walkdir = "2.5.0"
regex = "1.10.6"
crossterm = "0.28.1"
tokio = { version = "1.40.0", features = ["full"] }
