[package]
name = "check-for-unwrap"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
walkdir = "2.5.0"
regex = "1.5.4"
crossterm = "0.27.0"
tokio = { version = "1.38.0", features = ["full"] }
