[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = [
  "-Clinker=rust-lld.exe",
  "-Ctarget-cpu=native",
  "-Zshare-generics=n",
  "-Zthreads=0",
]
