[package]
name = "check-for-cringe-summaries"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
walkdir = "2.5.0"
tokio = { version = "1.41.1", features = ["full"] }
