[package]
name = "remove-mac-artifacts"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
walkdir = "2.5.0"
tokio = { version = "1.40.0", features = ["full"] }
anyhow = { version = "1.0.89", features = ["backtrace"] }
