[package]
name = "remove-extra-file-extensions"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
walkdir = "2.5.0"
tokio = { version = "1.38.0", features = ["full"] }
anyhow = "1.0.86"
