[package]
name = "sample-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
egui = "0.29.1"
eframe = "0.29.1"
rodio = "0.19.0"
tokio = { version = "1.40.0", features = ["full"] }
anyhow = "1.0.89"
walkdir = "2.5.0"
