[package]
name = "sample-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
egui = "0.29.1"
eframe = "0.29.1"
rodio = "0.20.1"
tokio = { version = "1.41.1", features = ["full"] }
anyhow = "1.0.93"
walkdir = "2.5.0"
