[package]
name = "sample-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
egui = "0.28.1"
eframe = "0.28.1"
rodio = "0.19.0"
tokio = { version = "1.26.0", features = ["full"] }
anyhow = "1.0.69"
walkdir = "2.5.0"
