[package]
name = "check-for-attributes"
version = "0.1.0"
authors = ["Balazs Horvath"]
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
regex = "1.10.5"
walkdir = "2.5.0"
crossterm = "0.27.0"
tokio = { version = "1.38.0", features = ["full"] }
