[package]
name = "create-empty-caption-files"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset-tools = { path = ".." }
walkdir = "2.5.0"
tokio = { version = "1.38.1", features = ["full"] }
anyhow = { version = "1.0.86", features = ["backtrace"] }
